### ISSUE TITLE
App devs can use DCAP attestation for OE enclaves on Windows

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [openenclave/openenclave#1043]
The existing OE support for Windows only depends on the old Intel AESM stack and is not yet integrated with new DCAP dependencies necessary for remote attestation features in OE. To enable this, we need to:

- [x] Add DCAP dependencies and configuration instructions for Windows to OE project (PR #1865 )
- [x] (External) Ensure that Azure/Intel DCAP provider libraries are available. 
- [x] Enable USE_LIBSGX configuration for Win32 code branches (PR #1865 )
- [x] Enable full report tests on Windows (PR #2081)

**Comment by anakrish** [comment]
@soccerGB

**Comment by anitagov** [comment]
bors try

**Comment by radhikaj** [comment]
@CodeMonkeyLeet I think this is done. Can we close it?

**Comment by CodeMonkeyLeet** [comment]
Completed
