### ISSUE TITLE
Core Testing: Expand testing of enclave management scenarios

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [openenclave/openenclave#23]
We need to flush out the details for behaviors of the enclave APIs an validate them. This includes:

- [x] Repeated enclave creation and termination (#359 )
- [x] Understandable errors returned on failed enclave creation at boundary conditions (#444 / #360  )
- [x] Enclave creation from a call out to host (#431)
- [x] Enclave behavior on abort() and unexpected exception (#432 )
- ~~Teardown semantics in enclave when host process is abruptly terminated~~ (Tracking as additional work item dependent on Intel driver update, see #589)
- [x] Teardown semantics when enclave thread is abruptly terminated (#432)
