### ISSUE TITLE
Core Testing: Expand testing of memory management support in enclaves

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [openenclave/openenclave#25]
We need to flush out the details for behaviors of the enclave APIs an validate them. This applies to the updated memory model within the enclave:

- [x] Review test coverage for allocation methods provided by the enclave runtime (PR #654, PR #655)
- [x] Validate attempts to alloc/free across the enclave boundary (PR #654)
- [x] Verify memory alloc/free is thread-safe (PR #654)
- [x] Performance tuning of allocation granularity within enclave (See https://github.com/Microsoft/openenclave/issues/25#issuecomment-419600109)
- [x] Memory teardown semantics in enclave when host process is abruptly terminated (Moved to #589)
