### ISSUE TITLE
Insufficient documentation for setting Intel SGX + open-enclave up on bare-metal environment (Ubuntu 18.04 LTS, SGX1-mode)

### ISSUE THREAD

**Issue by maverick-zhn** [openenclave/openenclave#2561]
After following the steps in the [documentation](https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/Contributors/SGX1), some of us consider (at least @mingweishih and I) this documentation insufficient to provide a complete description of how to set up **Intel SGX** (**driver**, **psw**, and **sdk**) and **Open-enclave** in **SGX1-mode**.

I propose to enhance the current documentation to include hidden steps that are necessary to have a complete workable environment. @mingweishih suggested opening a new issue for documenting this. I can gladly help with some information that I have collected after some tests with Ubuntu 18.04 LTS.

**ToDo** can include the following:
- [ ] Pre-Requisites for Intel SGX (driver, psw, sdk). A full set of references and useful information that can give you a hint if something is wrong or important background knowledge.
- [ ] Pre-Requisites for Open-Enclave.
- [ ] Description of known issues.
- [ ] A complete script/video of a sample installation from scratch (freshly installed Ubuntu.)
- [ ] A sample output tests for the `ctest -V`.
- [ ] Some other ideas go here ...

*Important notes*
- Do not assume that the user knows all the details about **Open-Enclave** or **Intel SGX**. At least provide references to inform.

**Comment by jhand2** [comment]
Thanks for writing this up. I have a couple comments/questions.

> * Pre-Requisites for Intel SGX (driver, psw, sdk). A full set of references and useful information that can give you a hint if something is wrong or important background knowledge.
> * Pre-Requisites for Open-Enclave.

This should be handled by the ansible script. If the ansible script doesn't work then thats a different problem.

> Description of known issues.

Which issues are you referring to? If you mean that secure boot needs to be disabled then yes I agree we should document this.

> A complete script/video of a sample installation from scratch (freshly installed Ubuntu.)

Basically the steps are:
1. Install prereqs with ansible
2. cmake
3. make
4. make install

Is this not captured in the existing document?

> A sample output tests for the ctest -V

All tests should succeed. In that case does it make sense to provide a sample of the output?

**Comment by maverick-zhn** [comment]
> Thanks for writing this up. I have a couple comments/questions.
> 
> > * Pre-Requisites for Intel SGX (driver, psw, sdk). A full set of references and useful information that can give you a hint if something is wrong or important background knowledge.
> > * Pre-Requisites for Open-Enclave.
> 
> This should be handled by the ansible script. If the ansible script doesn't work then thats a different problem.
> 
> > Description of known issues.
> 
> Which issues are you referring to? If you mean that secure boot needs to be disabled then yes I agree we should document this.
> 
> > A complete script/video of a sample installation from scratch (freshly installed Ubuntu.)
> 
> Basically the steps are:
> 
> 1. Install prereqs with ansible
> 2. cmake
> 3. make
> 4. make install
> 
> Is this not captured in the existing document?
> 
> > A sample output tests for the ctest -V
> 
> All tests should succeed. In that case does it make sense to provide a sample of the output?

@jhand2 

1) Yes, the pre-requisites should be handled by the ansible script. However, I did follow the docs and the environment was not ready for the tests. I had to install all Intel-related binaries from scratch.
2.) Yes, I was referring to any issues. Disabling **secure boot** was one, without your help it would have taken me way longer to figure that out.
3.) I was thinking of a demo version of the installation. But, yes you are right, perhaps it is not necessary.
4.) You are right.
Feel free to close this if you feel it is well-documented. My intention was to provide some help for this documentation.
Thanks.

**Comment by jhand2** [comment]
> 1.) Yes, the pre-requisites should be handled by the ansible script. However, I did follow the docs and the environment was not ready for the tests. I had to install all Intel-related binaries from scratch.
2.) Yes, I was referring to any issues. Disabling secure boot was one, without your help it would have taken me way longer to figure that out.
3.) I was thinking of a demo version of the installation. But, yes you are right, perhaps it is not necessary.
4.) You are right.
Feel free to close this if you feel it is well-documented. My intention was to provide some help for this documentation.
Thanks.

I'm mostly concerned with (1). If something doesn't work we should try to fix that. But I'm not sure what exactly didn't work (other than the driver installation because of secure boot).

As for (2) I agree we should document the secure boot issue. Is there anything else?

**Comment by maverick-zhn** [comment]
> > 1.) Yes, the pre-requisites should be handled by the ansible script. However, I did follow the docs and the environment was not ready for the tests. I had to install all Intel-related binaries from scratch.
> > 2.) Yes, I was referring to any issues. Disabling secure boot was one, without your help it would have taken me way longer to figure that out.
> > 3.) I was thinking of a demo version of the installation. But, yes you are right, perhaps it is not necessary.
> > 4.) You are right.
> > Feel free to close this if you feel it is well-documented. My intention was to provide some help for this documentation.
> > Thanks.
> 
> I'm mostly concerned with (1). If something doesn't work we should try to fix that. But I'm not sure what exactly didn't work (other than the driver installation because of secure boot).
> 
> As for (2) I agree we should document the secure boot issue. Is there anything else?

Nope, I would say that is it. Thank you @jhand2.

**Comment by jhand2** [comment]
Adding some extra options to this issue for when we get around to improving the documentation:
* We could provide (or ask intel to provide) a DKMS package for the isgx driver so that people don't have to disable secure boot
* We can provide instructions on how to manually sign the driver and then enroll the key in the Machine Owner Key (MOK) db. This would also allow for the driver to be installed with secure boot enabled.
