### ISSUE TITLE
Require explicit developer opt-in for OCalls made by the OE runtime

### ISSUE THREAD

**Issue by jhand2** [openenclave/openenclave#2676]
OE has many OCalls which it will make during execution of the runtime, without an enclave application explicitly making these OCalls. We should make developers explicitly import these into their own EDL files so that an the OE runtime cannot make an OCall which was not opted into.

This is a meta issue to track smaller work items to support this feature

* [x] Design documentation: PR https://github.com/openenclave/openenclave/pull/2482
* [x] Refactor EDL into smaller pieces of functionality: Issue https://github.com/openenclave/openenclave/issues/2585
* [x] Generate structures from annotated EDL: Isse https://github.com/openenclave/openenclave/issues/2666
* [ ] Additional documentation to aid developers in opting-out of specific ocalls: Issue #2719
* [ ] Publish EDL files with the SDK: PR #2816

Known bugs:
* [ ] #2817
* [ ] #2818

**Comment by jhand2** [comment]
Counting this as done when #2816 is merged. Additional enhancements will be tracked in other issues
