### ISSUE TITLE
Publish oecert tool

### ISSUE THREAD

**Issue by jhand2** [openenclave/openenclave#2898]
The oecert tool is an internal command-line tool which uses the OE attestation code to output a report and certificate from SGX.

This tool may be valuable for people writing SGX verification code. We should consider publishing this tool with the SDK so developers can use it to generate test data. This would also allow users to generate files to pass to the new host_verify sample: https://github.com/openenclave/openenclave/pull/2865

sub task:
- [x] Option to skip evidence verification - #3912 
- [x] Option to print verbose loggings (similar to oecertdump tool) - #3889 
- [x] Hardcoded enclave filename - #3919
- [x] Option to specify in-proc or out-of-proc quote generation - #3949
- [x] Option to not generate report/evidence/certificate output file - #3939 
- [x] Enclave must be signed. Check mrsigner when verification option is set - #3955
- [x] Add legal printout - #3955
- [x] Publish the tool - #3947
- [x] Rename tool and parameters - #4067

**Comment by yentsanglee** [comment]
oecert tool has to be run in SGX enclave-enabled environment. Users may build host verify sample from non-SGX VMs. One benefit for publishing oecert is so that the users can get a valid report from a SGX VM and copy the report file to a non-SGX VM for host verification.

If we decide to publish ocert, it should NOT be included in host verify package.

**Comment by jhand2** [comment]
Sure, I think just publishing it with the open-enclave package is fine.

**Comment by radhikaj** [comment]
Open another issue to make this tool TEE agile via plugins.

**Comment by yentsanglee** [comment]
Still more work to do.

**Comment by yentsanglee** [comment]
oeutil in tools folder.
