### ISSUE TITLE
Meta-Issue: Changes required to enable FLC/Non-FLC in one build

### ISSUE THREAD

**Issue by anakrish** [openenclave/openenclave#3272]
[FLC/Non-FLC in one build?](https://github.com/openenclave/openenclave/issues/3178) requires changes to the OE SDK to _allow building a single OE variant that works across all SGX variants (currently FLC/non-FLC) with appropriate runtime introspection._

This meta-issue captures that changes that would be needed to accomplish that goal.

- [x] **Necessary Cleanups** 
  Currently all the SGX libraries are dynamically loaded rather than being linked in, as used to be the case. The code base needs to be cleaned up to reflect this.
  - [x] Rename `OE_LINK_SGX_DCAP_QL`  to `OE_HAS_SGX_DCAP_QL` 
     PR #3270 
- [x] **Remove use of HAS_QUOTE_PROVIDER when building SDK libraries**
    This will ensure that the same libraries are produced whether SGX libraries are present in the build system or not.
    Attestation will be available only if the target system (the system in which enclaves are run) has the necessary quote provider libraries.
    PR #3273 
    Note: At this stage, HAS_QUOTE_PROVIDER will still be a cmake option. But internally it won't be used to build the libraries.
- [x] **Remove dependency on SGX headers when build SDK libraries**
  This will allow  the SDK libraries to be built on systems that don't have SGX headers installed.
  PR #3277 
- [x] **Remove use of OE_LINK_SGX_DCAP_QL** from tests.
  Some tests use this define to selectively perform assertions. Needs an investigation to determine if the tests can instead be converted to use a runtime query instead of a define to determine what assertions to perform.
PR #3282
- [x] **Remove use of HAS_QUOTE_PROVIDER** from package installation.
  PR #3288 
- [x] **Remove HAS_QUOTE_PROVIDER** as a cmake option.
  Tests will be enabled/disabled automatically based on the presence of quoting libraries on the system.
   PR #3288
- [ ] **Add non/SGX, non FLC machines to CI**
- [ ] **Update ansible and prereqs scripts**
   Update the scripts to remove dependencies if possible.
- [x] **Update docs** Remove references to HAS_QUOTE_PROVIDER.
  PR #3288

**Comment by anakrish** [comment]
#3270 Renames `OE_LINK_SGX_DCAP_Q` to `OE_HAS_SGX_DCAP_QL`

**Comment by anakrish** [comment]
#3273 Removes use of OE_LINK_SGX_DCAP_QL when building SDK libraries. This effectively removes any effect of HAS_QUOTE_PROVIDER cmake option when building the SDK libraries.

**Comment by radhikaj** [comment]
Broke CI items into its own issue #3581, see below.  Closing this since this is the build issue and work has been completed on it.
Add non/SGX, non FLC machines to CI
 Update ansible and prereqs scripts
Update the scripts to remove dependencies if possible.
