### ISSUE TITLE
App devs can expect an OE ELF enclave to behave consistently on Windows

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [openenclave/openenclave#376]
This story tracks that we have implemented feature parity for the Windows host implementation for Open Enclave, which consists for a tail of tasks and investigations:

- ~~#33 Implement mmap and convergent virtual memory management model for Windows~~
    - Not needed until we have to implement VADs for SGX2 in enclaves
- [x] #83 Implement POSIX time functions for Windows
- [ ] #85 Check if WaitForSingleEvent() or WaitOnAddress() should be used in mutex implementation
- [ ] #86 Check if CriticalSections should be used in place of Mutex 
- [x] #87 Determine appropriate implementation of OE_EXPORT on Windows
- [ ] #961 Factor out ELF-specific backtrace handling 
- [x] #978 Add tests for unsigned char, unsigned short, unsigned int & unsigned long

And also missing feature level parity implementations
- [x] #839 Add exception handling support on Windows 
- [x] #375 Implement crypto functions for host on BCrypt

This story is also related several additional stories:
- #37 App devs can debug a Windows app hosting an ELF enclave built with Open Enclave
- #39 App devs can expect Open Enclave unit tests as ELF on Windows to pass like Linux
- #377 App dev on Windows has a documented developer tooling story for Open Enclave 
- #378 App devs can refer to samples for building converged Windows/Linux enclave apps
- #1027 App Devs can run OE SDK tools on Windows
- #1043 App devs can use DCAP attestation for OE enclaves on Windows
