### ISSUE TITLE
Meta-Issue: Compiler Upgrade to clang-8

### ISSUE THREAD

**Issue by anakrish** [openenclave/openenclave#3786]
This meta-issue tracks the list of tasks that must be done to upgrade the compiler (clang) to a newer version.

- [x] OE SDK
  - [x] Update CMakeLists.txt to use newer compiler (#3805)
  - [x] Ensure that SDK builds and all tests pass
  - [x] Update CHANGELOG.md 
  - [x] Use newer compiler flags, if any, that improve security/performance
  - [x] Add LVI  compilerwrapper scripts (#3811)
  - [ ] ~~Update Windows clangw wrapper to use newer compiler~~ (Not needed. clangw always pick the default `clang`)
  - [x] Deprecate older compiler (#3811)
  - [x] Ensure that the build with LVI mitigation works
- [x] CI
  - [x] Add compiler to Linux CI images
  - [x] Add compiler to Windows CI images
  - [x] Add testing pipelines for new compiler
  - [x] Update nightly jobs to use new compiler
  - [x] Update ansible scripts to install newer compiler for Linux workflows
  - [x] Update install-prereqs scripts to install newer compiler for Windows workflows
  - [x] Drop support for compilers that are no longer supported (ie compilers that have been deprecated for at least a release).
  - [x]  Update and publish oecitools docker images
  - [ ] ~~Update CDPX images~~ (Not required. We use the Ansible scripts to build from a base image)
- [x] Devex
  - [x]  Update any hard-coded references to compiler version in VS/VS Code extensions
  - [x] Publish updated extensions
- [x] Documentation
  - [x]  Update documentation to refer to new compiler (#3811)

**Comment by anakrish** [comment]
bors delegate @rs--

**Comment by rs--** [comment]
#3810 handles the following:

- Add compiler to Linux CI images
- Add compiler to Windows CI images
- Add testing pipelines for new compiler
- Update ansible scripts to install newer compiler for Linux workflows
- Update install-prereqs scripts to install newer compiler for Windows workflows
- Drop support for compilers that are no longer supported (ie compilers that have been deprecated for at least a release).

**Comment by rs--** [comment]
1. "Update and publish oecitools docker images" is complete.
2. "Update nightly jobs to use new compiler" - will not do for this release: The nightly job of updating the images has been disabled right now due to an issue we're having with a Jenkins plugin. This shouldn't cause any issues as we're not looking to push any more updates to the Ansible files for this release.
3. "Update CDPX images" - not required for this release: The CDPx builds from a base image and installs dependencies using the Ansible scripts, so we don't need to do any updates to the CDPx images (@BRMcLaren, please correct me if I'm wrong)

**Comment by anakrish** [comment]
Thanks Rob!

**Comment by rs--** [comment]
All tasks completed, closing this issue.
