### ISSUE TITLE
App devs can expect Open Enclave unit tests as ELF on Windows to pass like Linux

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [openenclave/openenclave#39]
We need to ensure that the existing test suites pass for the equivalent implementation on Windows. This includes additional porting efforts as necessary for the tests hosts to run on Windows where appropriate.

- [x] #1008 Resize enclave tests to support Windows CI
- [x] #1033 Re-enable ELF enclave on Windows tests
- [x] Enable crypto tests on Windows (part of #375)
- [ ] #1034 Support libunwind and libc tests for ELF enclaves on Windows
    - Should encompass libcxx, libcxxrt, libc and libunwind test failures.

Remaining tests disabled on Windows:
- [ ] tests/memory (requires investigation after #632)
- [ ] tests/create-rapid (requires investigation after #632)
- [ ] tests/ecall_ocall (build failure on clangw on Windows) 
- [x] tests/tls_e2e (depends on socket support as part of PR #1960)

**Comment by mingweishih** [comment]
See #2394 for test/memory

**Comment by mingweishih** [comment]
Update:
tests/ecall_ocall is fixed by #2395 
tests/create-rapid is fixed by #2399

#1034 should be resolved after #2909 is merged
tests/memory should be fixed by #2950

After #2950 is merged, this issue can be closed.

**Comment by mingweishih** [comment]
Closing per #2950.
