### ISSUE TITLE
Meta-issue: Update MUSL to v1.2.2

### ISSUE THREAD

**Issue by RRathna** [openenclave/openenclave#3933]
Upgrade MUSL from v1.1.21 to v1.2.2
- [x] Fix tests/syscall/fs where when testing libc  ::stat(), use struct stat instead of struct oe_stat_t (#3941)
- [x] Add empty syscalls to accomodate musl linking to these new syscalls. Empty syscall - lstat, statx (#3943)
- [x] Implement syscall clock_nanosecond; add appropriate tests (#3973)
- [x] Update musl submodule to v1.2.2. Update libc and patches/ to align with v1.2.2 (#3943)
- [x] Audit tests/libc/ and add or remove relevant test cases (#3981)

**Comment by mingweishih** [comment]
Make sure to use https://github.com/openenclave/openenclave-musl

**Comment by RRathna** [comment]
All subtasks completed.  Need to update the change log after CI verification.
