### ISSUE TITLE
Open Enclave repo users have a good initial impression of the OSS project

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [openenclave/openenclave#395]
This story tracks the various fit & finish or fixes for "embarrassing" bugs that need to be addressed before publishing the Open Enclave repo as public OSS:

- [x] #57 Remove dead code before public preview
- [x] #146 Verify that OE code does not use assert() to control code flow in Release 
- [x] #303 Use Linux naming conventions internally
- [x] #393 Remove existing CMAKE based samples
- [x] #563 Remove unused Open Enclave tools 

This should be considered secondary to cleaning up technical issues in #396
