### ISSUE TITLE
App devs have a streamlined story for linking oeenclave/oecore 

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [openenclave/openenclave#400]
Currently, linking for an enclave app requires an arcane list of linker flags and specifically linking enclave libraries in a specific grouped order with whole-enclave linking. This additional bloats the size of the resulting enclave app, which is a concern given the limited EPC memory availability in ACC preview hardware. To address this story, we would need to:

- [x] #207 Relocate the enclave entry point to oeenclave
    - This also fixes: #320 Calling oe_verify_report from the host requires explicit linkage of oe_verify_report in enclave
- [x] #208 Eliminate need to specify OE_Main() entry point when linking
- [x] #330 Investigate optimal linker flags for use in Open Enclave
