### ISSUE TITLE
Meta-issue: Implement SGX 0-base enclaves for linux 

### ISSUE THREAD

**Issue by RRathna** [openenclave/openenclave#4026]
To implement 0-base enclave creation in OE SDK, the following are required:

- [x] Add required fields/variables to enable 0-base enclave creation.  (#4083)
- [x] Enable 0-base enclave creation through oesign config file and command line options. Add corresponding tests. (#4083, #4144)
- [x] Update documentation to reflect above feature addition. (#4115)
- [x] Add relevant tests (#4162)
- [x] Add sample (decided to not provide samples and use tests as example)

**Comment by RRathna** [comment]
The 0-base enclave creation and tests are complete and merged into codebase.
