### ISSUE TITLE
App devs can port their preferred libc into enclaves without affecting oeenclave

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [openenclave/openenclave#404]
oelibc currently implements several system primitives directly, which causes issues such as:

* The implementations are not sharable; the new libc being ported into an enclave must re-implement them.
* oecore cannot take a dependency on them. For example, malloc is not available to oecore, so it wastes memory in some cases doing static sized stack allocations instead.
* the imported libc library has an implicit contract with oecore, and a poor implementation can cause OE runtime to break in unintuitive ways, which we would like to avoid. 

Open Enclave currently already defines a libc subset serviced by custom oe_* prefixed methods in enclavelibc.h, and we should move that subset of functionality into oecore. This involves:

- [x] oelibc custom arc4random implementation should be consolidated in oecore #290 
- [x] Implement time primitives for libc in oecore #402
- [x] Move compile of dlmalloc into oe_malloc implementation in oecore #403

Once these things are done, we should verify that oeenclave and oecore only reference the internal oe_* libc subset methods instead of the general oelibc functions.

**Comment by johnkord** [comment]
@mikbras Do you think we can close this issue? Is there anything else we need to do?

**Comment by radhikaj** [comment]
@CodeMonkeyLeet Could we follow up on this one?

**Comment by CodeMonkeyLeet** [comment]
Outdated issue that's been addressed. Closing.
