### ISSUE TITLE
App devs can depend on a stable Open Enclave API surface that meets MS standard

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [openenclave/openenclave#411]
This story tracks sorting out all the API review feedback and also investigations we need to close on for the public preview release so that we minimize customer visible churn in the API surface:

- [x] #191 Verify that all function output variables are initialized on function exit 
- [x] #326 OE Result codes need to be documented
- [x] #407 simplify oe_get_report function signatures functionality 
- [x] #408 oe_identity should have comments on how fields are versioned documentation
- [x] #409 Open Enclave should prefix reports it generates with a custom header to facilitate parsing functionality 
- [x] #410 Open Enclave enums should always specify a size for the type functionality 
- [x] #455 Trim and refine the public API surface
- [x] #472 Add support for invoking OCalls by function pointer 
- [x] #473 Standardize buffer size on public APIs to use size_t 
- [x] #474 Disable re-entrancy on OCalls engineering functionality 
- [x] #476 Remove oe_thread from public API surface 
- [x] #477 Add support for identifying the originating enclave for Ocalls
- [x] #478 Rename authorID field in oe_identity to signerID 

Investigations that need to be closed regardless of whether we address them as part of this story:
- [x] #137 Clarify host function reachability
- [x] #168 OE_ThreadKeyDelete behavior neither conforms to pthreads, nor to WinAPI
- [x] #261 Remove OCall and related functionality from public API surface

Related feature requests that are currently out of scope:
* #206 Make Elf64_load work like dlopen using DT_RPATH / DT_RUNPATH
* #476 Add timeouts to thread-wait OCALLs
