### ISSUE TITLE
Open Enclave repo users have up-to-date documentation

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [openenclave/openenclave#416]
Related to providing a fit and finish for publishing the OSS project, this story tracks that included documentation is correct and useful:

- [x] #319 Update style guide to cover new Linux casing 
- [ ] #338 Updates needed to Getting Started doc
- [ ] #414 Update DesignOverview document
- [x] #415 Scrub all README.md files in the source tree for correctness

This also needs #419 Update Open Enclave HTML API reference, which is also tracked as part of story #417
