### ISSUE TITLE
Review OCALLs before public preview

### ISSUE THREAD

**Issue by mikbras** [openenclave/openenclave#458]
Review
--------

- [x] **OE_OCALL_CALL_HOST** - no change.
- [x] **OE_OCALL_MALLOC** - no change.
- [x] **OE_OCALL_REALLOC** - no change.
- [x] **OE_OCALL_FREE** - no change.
- [x] **OE_OCALL_MALLOC_DUMP** - no change.
- [x] **OE_OCALL_PUTS** - replaced by **OE_OCALL_PRINT** for **stderr** support in PR #646
- [x] **OE_OCALL_PUTCHAR** - replaced by **OE_OCALL_PRINT**  for **stderr** support in PR #646
- [x] **OE_OCALL_PRINT** - renamed to **OE_OCALL_WRITE** in PR #646
- [x] **OE_OCALL_THREAD_WAIT** - add argument to support timed waits (backlog, tracked by #635).
- [x] **OE_OCALL_THREAD_WAKE_WAIT** - add argument to support timed waits (backlog, tracked by #635).
- [x] **OE_OCALL_THREAD_WAKE** - no change.
- [x] **OE_OCALL_GET_QUOTE** - considered adding version argument, per discussion, not supporting cross-version compat for host-enclave interfaces.
- [x] **OE_OCALL_GET_QE_TARGET_INFO** - considered adding version argument, per discussion, not supporting cross-version compat for host-enclave interfaces.
- [x] **OE_OCALL_GETTIMEOFDAY** - removed by PR #459
- [x] **OE_OCALL_CLOCK_GETTIME** - removed by PR #459 
- [x] **OE_OCALL_STRFTIME** - removed by PR #459 
- [x] **OE_OCALL_NANOSLEEP** - removed by PR #459 
- [x] **OE_OCALL_SLEEP** - added by PR #459 
- [x] **OE_OCALL_GET_TIME** - added by PR #459 

Actions
---------
- Remove **OE_CALL_PUTS**
- Remove **OE_CALL_PUTCHAR**
- Rename **OE_OCALL_PRINT** to **OE_OCALL_WRITE**
- Add version number to **OE_OCALL_GET_QUOTE**
- Add version number to **OE_OCALL_GET_QE_TARGET_INFO**
- Add timeout to **OE_OCALL_THREAD_WAIT**
- Add timeout to **OE_OCALL_THREAD_WAKE_WAIT**
