### ISSUE TITLE
Fix install and configuration issues

### ISSUE THREAD

**Issue by mikbras** [openenclave/openenclave#799]
This issue tracks issues related to install and configuration of the **Open Enclave** package. These include.

- [x] Change default install location (in source tree) to **/opt/openenclave** (PR #800).
- [x] Introduce **.oeenclaverc** script to add binaries and pkg-config script to paths (PR #801).
- [x] Prevent install of **internal** directory (PR #790).
- [x] Install libraries under **lib64** directory instead of **lib** (deemed undesirable).
- [x] Modify samples to allow **make CC=gcc** (PR #815)
- [x] Remove use of **config.mak** file (PR #815)
- [x] Link to versioned SGX library.
- [x] Verify that samples build once installed (covered by automation).
- [x] Move **libc** and **libcxx** into the **openenclave** include directory. (PR #815)
